

[dependencies]
tokio = { version = "1", features = ["full"] }
tungstenite = "0.15"
tokio-tungstenite = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4"] }
hyper-hyper-space-core = "0.1.0" # Replace with the actual version